### ISSUE TITLE
Error Uncaught TypeError: Cannot read property 'filter' of undefined en la vista de tramites

### ISSUE THREAD

**Issue by jasonlll88** [ecos-codeaholics/factory-of-procedures-front#21]
This error appear with we pass to the windows tramites in the citizen session

Error Uncaught TypeError: Cannot read property 'filter' of undefined

**Comment by jasonlll88** [comment]
This error war resolve with the validation of data before to apply the filter

```
if (value==null) {
  return null;
}
```

If the pipe filter doesn't work maybe it could be by the data send by the back-end

**Comment by snaphuman** [comment]
You're right!. If no data is recieved from backend or if there is no default data (Because Mocks are some kind of default data), the filter cannot actuate. That's why it was returning an error related to a missing promise. Very clever. Thank's
