### ISSUE TITLE
[Procedures] problema con la vista de tramites en curso e histórico

### ISSUE THREAD

**Issue by snaphuman** [ecos-codeaholics/factory-of-procedures-front#22]
El filtro del listado de trámites no está funcionando y tampoco está mostrando la información de prueba.
Depurando la vista no se evidencia un error asociado a este comportamiento, se observa se está volcando una variable de tipo array que contiene los dos registros de prueba, pero no se están mostrando en la tabla.

**Comment by jasonlll88** [comment]
Puede ser debido a que los datos del dummy que había eran diferentes  a los que ya se están almacenando en la base de datos.
Lo mejor es hacer pull al front y al back, y antes de correr el back correr la prueba unitaria 
en src/test/java
procedureCreationTest 
esta prueba pobla la base de ddatos

**Comment by snaphuman** [comment]
Excelente @jasonlll88, en estos momentos estoy realizando tareas del trabajo por lo que podré hacer esta prueba en la tarde. Muchas gracias.

**Comment by snaphuman** [comment]
Se ha efectuado la prueba y se comprueba correcto funcionamiento
