### ISSUE TITLE
[Procedure] In the screen of functionary is not showing the data

### ISSUE THREAD

**Issue by jasonlll88** [ecos-codeaholics/factory-of-procedures-front#27]
The screen of  "formulario" in funcionary is not showing the data of the procedure,

![image](https://cloud.githubusercontent.com/assets/17026245/20464149/67aeb56e-af10-11e6-9c70-bd6b83c01817.png)

**Comment by snaphuman** [comment]
Im working on this rigth now. I'll reply this issue after completed

**Comment by snaphuman** [comment]
This form will use the rendering method that you implemented, to present dyamic values in the view

**Comment by snaphuman** [comment]
Its resolved in commit fe351189f17200b6cea0ef4f036958ce55e09e75.
Now functionary has access to procedure information 
![fabrica-tramites-funcionario](https://cloud.githubusercontent.com/assets/246425/20468897/5549e142-af69-11e6-967d-1ace91a9047f.png)
