### ISSUE TITLE
[documentos] tab documentos show an object

### ISSUE THREAD

**Issue by jasonlll88** [ecos-codeaholics/factory-of-procedures-front#28]
The view of "documentos" in both the functionary and the citizen is showing the word [object] it need to change to the link to download the document or whatever the citizen had uploaded

![image](https://cloud.githubusercontent.com/assets/17026245/20464178/eb9c6736-af10-11e6-893c-4842c93550a2.png)

**Comment by snaphuman** [comment]
Yep this need to be attended by @sebascardonac11

**Comment by snaphuman** [comment]
I have changed the layout for this page. So now, document url will be href value of anchor tag that represents a download button.
![fabrica-documentos](https://cloud.githubusercontent.com/assets/246425/20465691/86ebd472-af31-11e6-8db0-8db5091f41d3.png)

Greetings
