### ISSUE TITLE
[restaurar button] the button restaurar in the "docuementos" tab does work

### ISSUE THREAD

**Issue by jasonlll88** [ecos-codeaholics/factory-of-procedures-front#29]
We expect when the "restaurar" button in the tab of "documentos" restore the form to upload documents, but it doesn´t  work well (do not do anything).

![image](https://cloud.githubusercontent.com/assets/17026245/20464219/f9c0a2f4-af11-11e6-9831-60be874dd400.png)

**Comment by snaphuman** [comment]
Ok, I changed the markup yesterday but I havent seen any incorrect behavior. Thanks for looking

**Comment by jasonlll88** [comment]
The button was removed
