### ISSUE TITLE
[Citizen] Initiate procedure

### ISSUE THREAD

**Issue by snaphuman** [ecos-codeaholics/factory-of-procedures-front#3]
This feature should follow the Project's Functional Model and be part of procedures feature. 
At this first development stage, this component will use dummy content of a selected real-life procedure (which should be identified first) that handle both required data and required documents, besides pocedure basic information. The component consist in a user form that collects real-life procedure related data.

**Comment by jasonlll88** [comment]
The form has been linked with the data of the model-procudure stored in the DB. the porblem of blinding the data was resolve with the follow article

http://almerosteyn.com/2016/03/immutable-component-input-from-observable

There is missing make the request to save it in the DB

**Comment by jasonlll88** [comment]
We have validations and buttons now. there is missing to get the route of the file updated, and if its possible once upload the file the name should be appear in the field of upload file.

assigned to @sebascardonac11

**Comment by jasonlll88** [comment]
We already have the route an information, butttt with the new actulization of upload file the form is missing the upload file in the HTML5 validation files.
@sebascardonac11  and @davidfms22
