### ISSUE TITLE
It does not doing the Validation of the field (type file) to upload the cedula in the registration form

### ISSUE THREAD

**Issue by jasonlll88** [ecos-codeaholics/factory-of-procedures-front#35]
![image](https://cloud.githubusercontent.com/assets/17026245/20641196/c7f2c3ac-b3c0-11e6-8eb2-fbf245250f78.png)

**Comment by jasonlll88** [comment]
cedula es con tilde

**Comment by snaphuman** [comment]
Jajajaja vamos a tener que hacer este hotfix al proyecto lol

**Comment by jasonlll88** [comment]
jajajajaja
